# Installation and configuration

This section contains information on installing, removing and customising the program.

## Installing

Nuclear Morphology Analysis is designed to be runnable on Windows, Linux and MacOS, though it has been primarily designed and used on Windows. Since it requires a Java runtime, there are two ways to run the software

- with an included packaged Java runtime
- with a user installed version of Java (16 or higher)

### Windows

Option | Link | Info
-------|------|------
Portable | [Nuclear Morphology Analysis-${project.version}-windows.zip](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Nuclear_Morphology_Analysis-${project.version}-windows.zip) | Software and Java runtime in a portable format. Unzip the folder wherever you like and run 'Nuclear_Morphology_Analysis.exe'.
Installer | [Nuclear_Morphology_Analysis-${project.version}-windows.msi](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Nuclear_Morphology_Analysis-${project.version}-windows.msi) | Software and Java runtime in an installer for Windows. This will add the software to your list of installed programs, and create a start menu entry. May require administrator privileges depending on where you install.
Standalone Jar file | [Nuclear_Morphology_Analysis_${project.version}_standalone.jar](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Nuclear_Morphology_Analysis_${project.version}_standalone.jar)  | The jar file with all dependencies for users who want to use their own Java install.

You can also download a set of images suitable for testing the software from [https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Testing_mouse_image_set.zip](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Testing_mouse_image_set.zip).

### Linux
 
Option | Link | Info
-------|------|------
Linux portable | [Nuclear_Morphology_Analysis-${project.version}-linux.tar.gz](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Nuclear_Morphology_Analysis-${project.version}-linux.tar.gz) | Software and Java runtime in a portable format. Extract wherever you like and run 'launch.sh'. This version was packaged on Debian 11 with glibc 2.31. If you have issues with the packaged version, use the standalone jar below.
Standalone Jar file | [Nuclear_Morphology_Analysis_${project.version}_standalone.jar](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Nuclear_Morphology_Analysis_${project.version}_standalone.jar)  | The jar file with all dependencies for users who want to use their own Java install.

You can also download a set of images suitable for testing the software from [https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Testing_mouse_image_set.zip](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Testing_mouse_image_set.zip).

### MacOS

The software is not currently available packaged with the Java runtime. You will need to:

- Install Java 16 or higher on your Mac; an open source JDK can be downloaded and installed from the [Eclipse Temurin website](https://adoptium.net/temurin/releases/)
- Download [Nuclear_Morphology_Analysis_${project.version}_standalone.jar](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Nuclear_Morphology_Analysis_${project.version}_standalone.jar) 

Due to security permissions in recent versions of MacOS (Catalina and above) the program won't have access to user folders if launched by double-clicking the jar file. You should launch from the Terminal; open the Terminal, navigate to the directory containing the jar file, and launch the jar using `java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar`.

You can also download a set of images suitable for testing the software from [https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Testing_mouse_image_set.zip](https://bitbucket.org/bmskinner/nuclear_morphology/downloads/Testing_mouse_image_set.zip).

## Uninstalling

### Windows installer version

- Go to Programs and Features, find Nuclear Morphology Analysis in the list of installed programs, and click 'Uninstall'
- Nuclear Morphology Analysis also creates a folder in your home directory called `.nma`. Delete this folder too to remove all traces of the program.

### Portable versions - Windows, Linux and MacOS

- Delete the folder containing the program.
- Nuclear Morphology Analysis also creates a folder in your home directory called `.nma`. Delete this folder too to remove all traces of the program.

## Reporting issues {#issue-tracker}

If you find a bug in the software, you can report it in the [issue tracker](https://bitbucket.org/bmskinner/nuclear_morphology/issues?status=open). You will need to register a free account to post new issues.

## Configuration and user data

Nuclear Morphology Analysis creates a folder in your home directory called `.nma` on first launch, if this folder does not already exist. The folder is used to store:

- log files
- built-in rulesets for shapes we can detect
- custom rulesets for novel shapes you want to analyse
- custom program options

You can open the configuration folder via `Help > Open config directory`.

### Logs

The system state is logged when NMA is started in case debugging is needed. None of the logged data leaves your computer unless you explicitly send it. If you do find a bug or have a problem, and get in touch via the [issue tracker](#issue-tracker) you can upload a log file and it may help me track down the problem. There will be up to 5 log files, with `nma.0.log` containing the most recent logs. 

### Rulesets {#config-rulesets}

Rulesets are how we identify landmarks in nuclei. The program has default rulesets for mouse sperm, pig sperm and round nuclei.
These are stored in XML format. If you delete one of the default files, it will be recreated when the program is next launched. 

You can make your own ruleset files and save them in the `rulesets` folder; they will be included in the nucleus detection setup screen when the program is next launched. 

A ruleset needs to describe the landmarks in the nucleus, how we find them, which landmarks we use for orientation of the nucleus, and what measurements we should make. For example, the round nucleus ruleset is the simplest:

```{}
<?xml version="1.0" encoding="UTF-8"?>
<RuleSetCollection name="Round" application="VIA_MEDIAN" version="2.0.0" axis="Y">
  <Orient name="BOTTOM" value="Longest axis" />
  <Orient name="Y" value="Longest axis" />
  <Orient name="REFERENCE" value="Longest axis" />
  <Landmark name="Longest axis">
    <Ruleset type="Diameter profile">
      <Rule type="IS_MAXIMUM">
        <Value>1.0</Value>
      </Rule>
    </Ruleset>
  </Landmark>
  <Measurement>Perimeter</Measurement>
  <Measurement>Elongation</Measurement>
  <Measurement>Area</Measurement>
  <Measurement>Min diameter</Measurement>
  <Measurement>Aspect ratio</Measurement>
  <Measurement>Difference from median</Measurement>
  <Measurement>Bounding width</Measurement>
  <Measurement>Bounding height</Measurement>
  <Measurement>Regularity</Measurement>
  <Measurement>Ellipticity</Measurement>
  <Measurement>Circularity</Measurement>
</RuleSetCollection>
```

It contains one landmark, called `Longest axis`. This is defined as the point with the maximum value in the diameter profile. The landmark is used to specify three orientation marks: `BOTTOM`, `Y`, and `REFERENCE`. The `REFERENCE` point is the point from which profiles start. `BOTTOM` and `Y` indicate points that should be used to orient the nucleus, by rotating the nucleus such that this point is directly below the centre of mass. 

The `Measurement` values show the standard measures that will be calculated when nuclei are detected; several of these (e.g. aspect ratio) rely on the nucleus being orientable, which is why it is important to have at least one landmark that can be used for orientation.

#### Elements

RulesetCollection: the global settings for the ruleset

Name | Values
-----------|---------------
name | The name of the ruleset to display
application | How to apply the rules. Should almost always be `VIA_MEDIAN`
version | The software version the ruleset was created for
axis | The axis that should be prioritised when orienting. `Y` to prioritise vertical orientation, `X` to prioritise horizontal orientation

Measurement: the values that can be measured in this nucleus.

Orient: Maps landmarks to features used to orient the nucleus.

Name | Values
-----------|---------------
name | The name of the orientation mark. Must be one of `X`, `Y`, `TOP`, `BOTTOM`, `LEFT`, `RIGHT`
value | The name of the landmark that this mark is associated with. Must be a landmark name specified in a `Landmark` element

Landmark: Describes the features of interest in a nucleus, and the rules used to find them

Name | Values
-----------|---------------
name | The name of the landmark

The ruleset for each landmark is composed of one or more rules applied to a profile. Rules are applied in the order written.

Element | Name | Values
-----------|---------------|---------------
Ruleset | type | The profile type the rules are to be applied to. One of `Angle profile`, `Radius profile` or `Diameter profile`
Rule | type | the rule to apply
Rule | Value | These elements provide the values to each rule as described below.

#### Rule types

These are the valid rule types that can be used. When a rule is applied to a profile, it returns a new profile with a true or false value at every index, corresponding to whether the value in the profile matches the rule or not. This allows rules to be chained to find features of interest; an index excluded from a rule will never be included by a subsequent rule.

Rule | Values | Description
-----------|---------------|---------------
`IS_ZERO_INDEX` | `1` or `0` | If 1, finds the point at the first index of a profile. If 0, finds all points except the first index
`IS_MINIMUM`, `IS_MAXIMUM` | `1` or `0` | If 1, finds the minimum or maximum point in a profile. If 0, finds all points except the minimum or maximum
`IS_LOCAL_MINIMUM`, `IS_LOCAL_MAXIMUM` | First: `1` or `0`; second: an integer for window size |  If the first value is 1, finds local minima or maxima in a profile. If 0, finds all points except the local minima or maxima. A window size is needed to find minima and maxima; this is provided in the second value as an integer
`VALUE_IS_LESS_THAN`, `VALUE_IS_MORE_THAN` | A real number | Finds points that are more or less than the given absolute value
`INDEX_IS_LESS_THAN`, `INDEX_IS_MORE_THAN` | An integer | Finds points that have an index in their profile higher or lower than the value
`IS_CONSTANT_REGION` | First: the value to find; second: the minimum length of the region; third: the maximum deviation from the desired value | Finds regions with a constant value over at least a given number of indexes. The stringency of the constant calue can be altered.
`FIRST_TRUE`, `LAST_TRUE` | `1` or `0` | Designed to be applied after a previous rule. If 1, finds the first/last index matching the rule condiions. If 0, finds all except the first index matching the rule conditions
`INDEX_IS_WITHIN_FRACTION_OF`, `INDEX_IS_OUTSIDE_FRACTION_OF` | A real number between 0 and 1 | Finds indexes that are greater or less than the given fraction of the profile


### Custom options {#config-file}

Custom options are set in the `config.ini` file in the configuration directory. They are in the format `OPTION=VALUE`. The following options can be set, and will take effect when the program is next launched:

Key        | Allowed Values | Effect
-----------| ---------------|--------------
`DEFAULT_IMAGE_SCALE` | A positive number _e.g._ `18.0` | Sets the default scale for converting pixels to microns
`DEFAULT_RULESET` | A ruleset file name from the rulesets directory _e.g._ `Mouse sperm` | Sets the default ruleset for landmark detection
`DEFAULT_COLOUR_SWATCH` | `REGULAR_SWATCH` `ACCESSIBLE_SWATCH` `NO_SWATCH` | Sets the default colouring of datasets and segments
`DEFAULT_DIR` | directory with backslashes escaped _e.g._ `C:\\path\\to\\folder`    | Sets the default folder for exporting data
`DEFAULT_DISPLAY_SCALE` | `PIXELS` `MICRONS` | Sets the default scale to display in charts and tables
`REFOLD_OVERRIDE` |  `true` `false`| If true, the 'best-fit nucleus' method will always be used instead of the position averaging method
`USE_ANTIALIASING` | `true` `false` | Sets the default value for the 'Use anti-aliasing' option. False makes charts faster to render, but not as pretty.
`USE_DEBUG_INTERFACE` | `true` `false` | If true, shows debugging information in some charts
`USE_GLCM_INTERFACE` | `true` `false` | If true, allows GLCM measurements for nuclei
`FILL_CONSENSUS` | `true` `false` | Sets the default value for the 'Fill consensus' checkbox in the view menu 
`CHECK_FOR_UPDATES` | `true` `false` | If true, the software will check for new versions on launch. If false, updates can still be checked manually via `Help > Check for updates`
