# Other topics

This section contains information on more advanced use of NMA.

## Command line use

Nuclear Morphology Analysis is designed to be runnable via the command line for *some* of the available functions. Things that require visual interaction such as moving landmarks obviously don't have a neat CLI equivalent, but you can create new analyses and export data from lots of datasets more easily than going through the UI.

The examples below use the cross platform standalone jar with a system installation of Java. Note that these arguments will not work with the Windows exe version.

To see the sub-commands:
```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar -h
```

The available sub-commands are:

Command | Use to...
--------|-----------
`detect`| create a new nmd file by detecting nuclei in directory of images and apply clustering or signal detection according to a predefined options file. An options file can be exported from a dataset you have already created and analysed via the UI.
`export`| export data from an existing nmd file for use in other programs
`modify` | add new data to an existing nmd file
`merge` | merge existing nmd files into a new nmd file

### `detect` 

To see all the detect options:
```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar detect -h
```

For example, to run a new analysis:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar detect --directory /path/to/image/directory --options /path/to/options/file.xml
```

### `export`

These commands correspond to the UI menu options in `Dataset > Export...`. 
To see all the export options:
```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar export -h
```

To export nuclear measurements from an `.nmd` file:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar export --file /path/to/file.nmd --measurements
```

Export options can be combined. To export nuclear signal measurements and nuclear measurements:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar export --file /path/to/file.nmd --measurements --signals
```

Exported data files will be created in the same directory as the `nmd` file.

### `modify`

These commands correspond to the UI menu options in `Dataset`. 
To see all the modify options:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar modify -h
```

There are currently two operations available:

1. Adding clusters to an nmd file that have been defined externally. For example, you exported nuclear measurements, clustered them in another stats package, exported a [cluster format file](#import-cluster-method), and now you want to look at the consensus shape of each cluster:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar modify --file /path/to/existing.nmd --cluster-file /path/to/cluster/file
```

2. Adding data based on analysis options. For example, you have an nmd file and you want to add nuclear signals or clusters according to the options from another dataset.

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar modify --file /path/to/existing.nmd --options /path/to/options/file.xml
```

### `merge`

These commands correspond to the UI menu options in `Dataset>Merge`.

To see all the merge options:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar merge -h
```

This can be used to merge existing nmd files into one larger dataset. The individual files must all have the same nucleus type:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar merge --output /path/to/new.nmd --input /path/to/input1.nmd /path/to/input2.nmd
```

Note above you can list multiple nmd files after the `--input` argument. You can also use standard shell wildcards to merge arbitrary numbers of nmd files:

```
java -jar Nuclear_Morphology_Analysis_${project.version}_standalone.jar merge --output /path/to/new.nmd --input *.nmd
```

## Detection of nuclei from text files {#text-analysis}

This is available from the File menu 'New analysis' > 'Use text file of nucleus coordinates'. An analysis setup screen will be shown where you will be asked to choose a folder containing one or more text files that describe the outlines of objects to analyse.

A separate text file should be present for each source image to be analysed. The files should contain tab separated values. The default settings would expect columns `Image`, `Object`, `x` and `y`. `Image` contains the path to the source image. `Object` is an integer containing the object to which an outline coordinate belongs. `x` and `y` contain the floating point pixel coordinates of a point in the object outline.

For example, this shows the first three points in the outline of the first object within the file `image_a.jpg`:
```
Image	Object	x	y
/path/to/image_a.jpg	0	204.525	907.2
/path/to/image_a.jpg	0	202.5	909.225
/path/to/image_a.jpg	0	202.5	984.14996
```

If your file has columns in a different order, you can specify the column indexes that correspond to the required columns. The column names in your file do not need to match those given here.

You may also optionally add a landmark file. This is a single file that contains the locations of landmarks in the cells. The landmark file is a tab-separated file with the following format:
```
Dataset	ImageFile	CellID	NucleusID	BoundingXMin	BoundingXMax	BoundingYMin	BoundingYMax	LandmarkName	LandmarkX	LandmarkY
Mouse	/path/to/image_a.jpg	70e1f840-67ec-4b7e-bd7d-cd2b03c13de5	00000000-2d16-bf21-ffff-ffffee0cd821	560.035888671875	675.563232421875	334.50482177734375	430.5233154296875	Tip of hook	675.242431640625	421.01898193359375	
Mouse	/path/to/image_a.jpg	70e1f840-67ec-4b7e-bd7d-cd2b03c13de5	00000000-2d16-bf21-ffff-ffffee0cd821	560.035888671875	675.563232421875	334.50482177734375	430.5233154296875	Ventral upper	631.1483764648438	395.4069519042969	
```

Each line contains one landmark in one cell. The cell bounding box is provided to allow landmarks to be matched to the correct cell. The values in the `ImageFile` column must match the values in the `Image` column from the outlines file, as this is how corresponding images are matched. The Dataset, CellID and NucleusID values are not used to identify cells.

If no landmark file is provided, landmarks will be detected using profiles via the standard method.

Profiles will only be segmented if the Segment profiles option is selected.